### ISSUE TITLE
Bug：Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LitterWindwind** [microsoft/SpareNet#1] opened 2021-04-12 02:36 UTC
Hi，Following the instructions strictly， I run test.py, report as follow:
```
INFO: - Finish building dataset.
Residualnet
generating 2D grid
DEBUG: - Parameters in net_G: 82562191.
INFO: - Recovering from weight/SpareNet.pth ...
INFO: - Recover complete. Current epoch = #150; best metrics = {'F-Score': 0.6606881591485739, 'ChamferDistance': 0.5150378787751227, 'EMD': 1.8626600753050297}.
INFO: - Start validating.
INFO: - Test[1/1200] Taxonomy = 02691156 Sample = e431f79ac9f0266bca677733d59db4df0 Losses = ['20.0666', '17.4211'] Metrics = ['0.6629', '0.4095', '1.7410']
Segmentation fault (core dumped)
```

**Comment by AlphaPav** [comment] 2021-04-12 03:35
Hello, thanks for your question! We repeated the experiments and didn't encounter such a bug. 

- What are your Python, PyTorch, and CUDA versions? It might be caused by a version mismatch. 

- Could you set "num_workers =1"  to DataLoader and debug in single-step mode?  There is one reason for such failure: you might be working with a lot of data and your RAM is full.  

https://stackoverflow.com/a/31048386
https://discuss.pytorch.org/t/guidelines-for-assigning-num-workers-to-dataloader/813

**Comment by LitterWindwind** [comment] 2021-04-13 09:18
Thank you for your reply!
Can you provide your version of pytorch？
At first， I run `conda install pytorch cudatoolkit=10.1 torchvision -c pytorch` 
but the hashrate of 3080 does not match the cuda version，leading to cuda error.
So I upgrade the cuda version, leading to Segmentation fault (core dumped).

I try some version as follow(RTX 3080):
cuda 10.1 pytorch1.7.1   cuda error:no kernel image is ....
cuda 11.0 pytorch1.7.1   Segmentation fault (core dumped)  
cuda11.1  pytorch1.8.1   ImportError: /home/qiuf/.cache/torch_extensions/cd/cd.so: undefined symbol: _ZNK2at6Tensor4sizeEl

**Comment by AlphaPav** [comment] 2021-04-18 03:18
Hey @LitterWindwind 
It looks like it's an issue with PyTorch and CUDA versions. 

We used:
Python：3.6.12
Pytorch：1.6 or 1.7
CUDA：10.2 or 10.1 or 11.2

Hope it helps!

**Comment by LitterWindwind** [comment] 2021-04-23 07:16
Hey @AlphaPav 
Sorry to bother you with this question again.
I can train the model, but after completing an epoch，it will report
`INFO: - [Epoch 1/150][Batch 4829/4829] BatchTime = 2.256 (s) Losses = ['23.5520', '33.5317']
INFO: - [Epoch 1/150] EpochTime = 13192.311 (s) Losses = ['32.5895', '93.8642']
INFO: - Start validating.
INFO: - Test[1/1200] Taxonomy = 02691156 Sample = e431f79ac9f0266bca677733d59db4df0 Losses = ['68.3223', '17.6855'] Metrics = ['0.6603', '0.8762', '1.7702']
Segmentation fault (core dumped)`
It shows that the problem has nothing to do with the environment and is still a problem with the test code part.

I took a moment to locate where the error occurred.
When the code runs to this function：
`    def save_item_val_info(self, data):
        self.test_metrics.update(self.metrics)
        if self.taxonomy_id not in self.category_metrics:
            self.category_metrics[self.taxonomy_id] = AverageMeter(um.Metrics.names())
        self.category_metrics[self.taxonomy_id].update(self.metrics)

        if self.model_idx % self.config.TRAIN.log_freq == 0:
            self.logger.info(
                "Test[%d/%d] Taxonomy = %s Sample = %s Losses = %s Metrics = %s"
                % (
                    self.model_idx + 1,
                    self.n_batches,
                    self.taxonomy_id,
                    self.model_id,
                    ["%.4f" % l for l in self.test_losses.val()],
                    ["%.4f" % m for m in self.metrics],
                )
            )
        self.inference(data)`
Could you please provide some suggestions about this？
Thank you for your reply!

**Comment by orenkatzir** [comment] 2021-07-28 06:00
@AlphaPav I also got a segmentation fault, not exactly from this line of code, but in general.
I am running on a docker with exactly the software and driver versions you have specified.
However, running the code as is, i.e. vanilla, was OK.
But when I try to change a bit the transformation of the incoming point clouds, I am getting segmentation fault after few epochs (random number of epochs, usually in the middle of the second)
Do you expect such a change to cause a segmentation fault? Maybe something with input point cloud has to be normalized?

**Comment by AlphaPav** [comment] 2021-07-28 12:22
We didn't expect such a segmentation fault. What transformation did you use? @orenkatzir

**Comment by orenkatzir** [comment] 2021-07-28 12:32
Very basic ones: Rotation and translation

**Comment by AlphaPav** [comment] 2021-09-12 02:48
Hi! I assume the issue was resolved, so I am closing the issue. Feel free to reopen if you still have questions.
Thanks.

**Closed by AlphaPav** 2021-09-12 02:48 UTC
